version = 0.1
[default.deploy.parameters]
stack_name = "prism-dev-new"
resolve_s3 = true
s3_prefix = "prism-dev-new"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
