version = 0.1
[default.deploy.parameters]
stack_name = "prism3"
resolve_s3 = true
s3_prefix = "prism3"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
