spring:
  datasource:
    url: url
    username: username
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true


service:
  frontend-origin: origin
  sender-email: email