spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prism
    username: root
    password: pcs8437!

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: prism.works1@gmail.com
    password: gyfgzadscolwaceh
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.htmlㅍ
    disable-swagger-default-url: true


service:
  frontend-origin: http://localhost:8080
  sender-email: no-reply@PRismWorks.com