#spring:
#  datasource:
#    url:
#    username:
#    password:
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
